pasterizers/pasterizers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls', namespace="root")),
]

pasterizers/root/urls.py
from django.urls import path
from . import views


app_name = "root"
urlpatterns = [
    path("", views.index, name="index"),
    path("PET-4/", views.pet4, name="pet4"),
    path("GLASS-6/", views.glass6, name="glass6"),
    path("CAN-1/", views.can1, name="can1"),
    path("PET-2/", views.pet2, name="pet2"),
    path("PET-KEG/", views.petkeg, name="petkeg"),
    path("KEG/", views.keg, name="keg"),
    path("help/", views.help, name="help"),
    path("contacts/", views.contacts, name="contacts"),
    path("review/", views.review, name="review"),
    ]

pasterizers/root/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class CreatedModel(models.Model):
    """Абстрактная модель. Добавляет дату регистрации."""
    reg_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True,
    )

    class Meta:
        abstract = True


class Persons(CreatedModel):
    name = models.TextField(
        verbose_name='Имя',
        help_text='Имя сотрудника')
    sirname = models.TextField(
        verbose_name='Фамилия',
        help_text='Фамилия сотрудника')
    email = models.EmailField()
    date_of_birth = models.DateField()

    def __str__(self) -> str:
        return self.sirname

    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employes'


class Media(models.Model):
    title = models.TextField(
        verbose_name='Название',
        help_text='Название произведения'
    )
    actors = models.ManyToManyField(Persons)

    def __str__(self) -> str:
        return self.title

pasterizers/root/forms.py
from django import forms


class ParameterForm(forms.Form):
    CHOICES = [
    ('temp_past', 'Температура в камере пастеризации'),
    ('press_past', 'Давление в камере пастеризации'),
    ('temp_cool', 'Температура охлаждения'),
    ('pu', 'Коэффициент пастеризации'),
    ('o2', 'Показания кислородомера'),
    ('flow', 'Поток')
    ]
    CHOICES_hour = [('0', '0'),
                    ('1', '1'),
                    ('2', '2'),
                    ('3', '3'),
                    ('4', '4'),
                    ('5', '5'),
                    ('6', '6'),
                    ('7', '7'),
                    ('8', '8'),
                    ('9', '9'),
                    ('10', '10'),
                    ('11', '11'),
                    ('12', '12'),
                    ('13', '13'),
                    ('14', '14'),
                    ('15', '15'),
                    ('16', '16'),
                    ('17', '17'),
                    ('18', '18'),
                    ('19', '19'),
                    ('20', '20'),
                    ('21', '21'),
                    ('22', '22'),
                    ('23', '23'),]
    day = forms.DateField(widget=forms.SelectDateWidget)
    parameters = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=CHOICES,
        required=False,)
    hour_from = forms.ChoiceField(
        choices=CHOICES_hour,
        required=False) 
    hour_to = forms.ChoiceField(
        choices=CHOICES_hour,
        required=False)       

pasterizers/root/views.py
from django.shortcuts import render
from .forms import ParameterForm
from django.db import connection
import matplotlib.pyplot as plt


plt.switch_backend('agg')


def index(request):
    return render(request, 'root/index.html')


def plot_figure(form, table):
    cursor = connection.cursor()
    params_list = ['temp_past', 'press_past', 'temp_cool', 'pu', 'o2', 'flow']
    day = form.cleaned_data.get('day')
    params = form.cleaned_data.get('parameters')
    hour_from = form.cleaned_data.get('hour_from')
    hour_to = form.cleaned_data.get('hour_to')
    cursor.execute(
        f"SELECT time FROM {table} WHERE date = '{day}'" +
        f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
    timeline = cursor.fetchall()
    timeline_format = []
    for i in timeline:
        timeline_format.append(str(*i))
    if params_list[0] in params:
        cursor.execute(
            f"SELECT {params_list[0]} FROM {table} WHERE date = '{day}'" +
            f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
        temp_past = cursor.fetchall()
        plt.plot(timeline_format, temp_past)
    if params_list[1] in params:
        cursor.execute(
            f"SELECT {params_list[1]} FROM {table} WHERE date = '{day}'" +
            f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
        press_past = cursor.fetchall()
        plt.plot(timeline_format, press_past)
    if params_list[2] in params:
        cursor.execute(
            f"SELECT {params_list[2]} FROM {table} WHERE date = '{day}'" +
            f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
        temp_cool = cursor.fetchall()
        plt.plot(timeline_format, temp_cool)    
    if params_list[3] in params:
        cursor.execute(
            f"SELECT {params_list[3]} FROM {table} WHERE date = '{day}'" +
            f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
        pu = cursor.fetchall()
        plt.plot(timeline_format, pu) 
    if params_list[4] in params:
        cursor.execute(
            f"SELECT {params_list[4]} FROM {table} WHERE date = '{day}'" +
            f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
        o2 = cursor.fetchall()
        plt.plot(timeline_format, o2)
    if params_list[5] in params:
        cursor.execute(
            f"SELECT {params_list[5]} FROM {table} WHERE date = '{day}'" +
            f" AND time BETWEEN '{hour_from}:00:00' AND '{hour_to}:00:00';")
        flow = cursor.fetchall()
        plt.plot(timeline_format, flow)
    plt.savefig('static/figures/figure.png')
    plt.clf()
    cursor.close()    


def line_view(request, page, table):
    submitbutton = request.POST.get('submit')
    form = ParameterForm(request.POST or None)
    if form.is_valid():
        plot_figure(form, table)
        context = {
            'form': form,
            'submitbutton': submitbutton,
        }
        return render(request, page, context)
    return render(request, page, {'form': form})    


def pet4(request):
    return line_view(request, 'root/PET-4.html', 'pet4')


def glass6(request):
    return line_view(request, 'root/GLASS-6.html', 'glass6')      


def can1(request):
    return line_view(request, 'root/CAN-1.html', 'can1')


def pet2(request):
    return line_view(request, 'root/PET-2.html', 'pet2')


def petkeg(request):
    return line_view(request, 'root/PET-KEG.html', 'petkeg')


def keg(request):
    return line_view(request, 'root/KEG.html', 'keg')


def help(request):
    return render(request, 'root/help.html')


def contacts(request):
    return render(request, 'root/contacts.html')


def review(request):
    return render(request, 'root/review.html')

pasterizers/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <h1>О разработчике</h1>
  <p>
    Тут я размещу информацию о себе, используя свои умения верстать.
    Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
  </p>
{% endblock %} 

pasterizers/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h1>Вот что я умею</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
  </div>
{% endblock %} 

pasterizers/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% load static %} 
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>
      {% block title %}Заголовок{% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include "includes/header.html" %}
    </header>
    <main>
      {% block content %}content{% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include "includes/footer.html" %}
    </footer>
  </body>

pasterizers/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %} 

pasterizers/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <a href="{% url 'root:index' %}">Главная</a>
  <a href="{% url 'root:help' %}">Справка</a>
  <a href="{% url 'root:contacts' %}">Контакты</a>
  <a href="{% url 'root:review' %}">Обратная связь</a>
  <p>© {{ year }} Copyright <span> Pcontrol</span></p>    
</footer> 

pasterizers/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'root:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">control</span>
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view %}
        <li class="nav-item"> 
          <a class="nav-link {% if view == 'root:help' %}active{% endif %}" href="{% url 'root:help' %}">Справка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view == 'root:contacts' %}active{% endif %}" href="{% url 'root:contacts' %}">Контакты</a>
        </li>
      {% endwith %}
    </ul>  
  </div>
</nav>  
<nav class="navbar navbar-light" style="background-color: LightGrey">
  <div class="container">
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view %}
        <li class="nav-item"> 
          <a class="nav-link {% if view == 'root:pet4' %}active{% endif %}" href="{% url 'root:pet4' %}">PET-4</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view == 'root:glass6' %}active{% endif %}" href="{% url 'root:glass6' %}">GLASS-6</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view == 'root:can1' %}active{% endif %}" href="{% url 'root:can1' %}">CAN-1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view == 'root:pet2' %}active{% endif %}" href="{% url 'root:pet2' %}">PET-2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view == 'root:petkeg' %}active{% endif %}" href="{% url 'root:petkeg' %}">PET-KEG</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view == 'root:keg' %}active{% endif %}" href="{% url 'root:keg' %}">KEG</a>
        </li>
      {% endwith %}
    </ul>
  </div>
</nav>  

pasterizers/templates/includes/plot_figure.html
{% load static %}
<form action="" method="POST">
  {% csrf_token %}
  <div class="alert alert-light">
    <p>Выберите дату</p>
    {{ form.day }}
  </div>
  <div class="alert alert-dark">
    <p>Выберите контролируемые параметры</p>
    {{ form.parameters }}
  </div>
  <div class="alert alert-dark">
    <p>Выберите время</p>
    <table>
      <tr>
        <td>Час от</td>
        <td>{{ form.hour_from }}</td>
      </tr>  
      <tr>  
        <td>Час до</td>
        <td>{{ form.hour_to }}</td>
      </tr>
    </table>  
  </div>
  <button class="btn btn-secondary" type="submit" name="submit" value="Submit">Построить график</button>
  {% if submitbutton == 'Submit' %}
    <img src="{% static 'figures/figure.png' %}" width="1200" height="500" class="d-inline-block align-top" alt="">
  {% endif %}

pasterizers/templates/root/CAN-1.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
  {% include "includes/plot_figure.html" %}  
{% endblock %}

pasterizers/templates/root/GLASS-6.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
  {% include "includes/plot_figure.html" %}  
{% endblock %}

pasterizers/templates/root/KEG.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
  {% include "includes/plot_figure.html" %}  
{% endblock %}

pasterizers/templates/root/PET-2.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
  {% include "includes/plot_figure.html" %}  
{% endblock %}

pasterizers/templates/root/PET-4.html
{% extends "base.html" %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
  {% include "includes/plot_figure.html" %}
{% endblock %}

pasterizers/templates/root/PET-KEG.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
  {% include "includes/plot_figure.html" %}  
{% endblock %}

pasterizers/templates/root/contacts.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
    
{% endblock %}

pasterizers/templates/root/help.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
    
{% endblock %}

pasterizers/templates/root/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
    <div class="container py-5">
      <h3>Сбор технологических данных доступных установок для пастеризации</h3>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">
            <button class="button bt-secondary">
              <a class="nav-link" href="{% url 'root:pet4' %}">PET-4</a>
            </button>
            <p1>Производитель:</p1>
            <p>
              APV gmbh
            </p>
          </th>
          <td>
            <img src="{% static 'img/01.jpg' %}" width="300" height="300" class="d-inline-block align-top" alt="">
          </td>
          <td>
            <p><strong>Параметры, отображаемые на графике:</strong></p>
            <div class="p-3 mb-2 bg-secondary text-white">- температура в камере пастеризации</div>
            <div class="p-3 mb-2 bg-info text-black">- давление в камере пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- температура охлаждения</div>
            <div class="p-3 mb-2 bg-info text-black">- коеффициент пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- показания кислородомера</div>
            <div class="p-3 mb-2 bg-info text-black">- поток пастеризатора</div>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="p-3 mb-2 bg-secondary text-white">GLASS-6</div>
            <p1>Производитель:</p1>
            <p>
              APV gmbh
            </p>
          </th>
          <td>
            <img src="{% static 'img/02.jpg' %}" width="300" height="300" class="d-inline-block align-top" alt="">
          </td>  
          <td>
            <p><strong>Параметры, отображаемые на графике:</strong></p>
            <div class="p-3 mb-2 bg-secondary text-white">- коеффициент пастеризации</div>
            <div class="p-3 mb-2 bg-info text-black">- поток пастеризатора</div>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="p-3 mb-2 bg-secondary text-white">CAN-1</div>
            <p1>Производитель:</p1>
            <p>
              APV gmbh
            </p>
          </th>
          <td>
            <img src="{% static 'img/03.jpg' %}" width="300" height="300" class="d-inline-block align-top" alt="">
          </td>
          <td>
            <p><strong>Параметры, отображаемые на графике:</strong></p>
            <div class="p-3 mb-2 bg-secondary text-white">- показания кислородомера</div>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="p-3 mb-2 bg-secondary text-white">KEG</div>
            <p1>Производитель:</p1>
            <p>
              APV gmbh
            </p>
          </th>
          <td>
            <img src="{% static 'img/04.jpg' %}" width="300" height="300" class="d-inline-block align-top" alt="">
          </td>
          <td>
            <p><strong>Параметры, отображаемые на графике:</strong></p>
            <div class="p-3 mb-2 bg-secondary text-white">- температура в камере пастеризации</div>
            <div class="p-3 mb-2 bg-info text-black">- давление в камере пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- температура охлаждения</div>
            <div class="p-3 mb-2 bg-info text-black">- коеффициент пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- показания кислородомера</div>
            <div class="p-3 mb-2 bg-info text-black">- поток пастеризатора</div>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="p-3 mb-2 bg-secondary text-white">PET-2</div>
            <p1>Производитель:</p1>
            <p>
              APV gmbh
            </p>
          </th>
          <td>
            <img src="{% static 'img/05.jpg' %}" width="300" height="300" class="d-inline-block align-top" alt="">
          </td>
          <td>
            <p><strong>Параметры, отображаемые на графике:</strong></p>
            <div class="p-3 mb-2 bg-secondary text-white">- температура в камере пастеризации</div>
            <div class="p-3 mb-2 bg-info text-black">- давление в камере пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- температура охлаждения</div>
            <div class="p-3 mb-2 bg-info text-black">- коеффициент пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- показания кислородомера</div>
            <div class="p-3 mb-2 bg-info text-black">- поток пастеризатора</div>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="p-3 mb-2 bg-secondary text-white">PET-KEG</div>
            <p1>Производитель:</p1>
            <p>
              APV gmbh
            </p>
          </th>
          <td>
            <img src="{% static 'img/06.jpg' %}" width="300" height="300" class="d-inline-block align-top" alt="">
          </td>
          <td>
            <p><strong>Параметры, отображаемые на графике:</strong></p>
            <div class="p-3 mb-2 bg-secondary text-white">- температура в камере пастеризации</div>
            <div class="p-3 mb-2 bg-info text-black">- давление в камере пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- температура охлаждения</div>
            <div class="p-3 mb-2 bg-info text-black">- коеффициент пастеризации</div>
            <div class="p-3 mb-2 bg-secondary text-white">- показания кислородомера</div>
            <div class="p-3 mb-2 bg-info text-black">- поток пастеризатора</div>
          </td>
        </tr>
      </tbody>
    </table> 
{% endblock %}

pasterizers/templates/root/review.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Пастеризаторы
{% endblock %}
{% block content %}
    
{% endblock %}